---
title: "FINAL"
author: "Sizhu Jiang, Sirui Hu, Meredith Jin, Joyce Liu, Fang Zhou"
date: "2020/4/11"
output: html_document
---

```{r}
library(tidyverse)
library(forcats)
library (Hmisc)
library (SASxport)
PAQ <- read.xport ("PAQ_I.xpt")
HSQ <- read.xport("HSQ_I.xpt")
```

```{r}
# View(PAQ)
head(PAQ)
head(HSQ)
data2 <- PAQ %>%
  left_join(HSQ,by="SEQN")%>%
  select(SEQN,PAQ677,PAQ678,HSD010)%>%
  drop_na() %>%
  filter(PAQ677 != 99 ) 

data2$HSD010_1 <- factor(data2$HSD010,levels=c("Excellent","Very Good","Good","Fair","Poor"))
data2$HSD010_1[data2$HSD010 == 1]<-"Excellent"
data2$HSD010_1[data2$HSD010 == 2]<-"Very Good"
data2$HSD010_1[data2$HSD010 == 3] <-"Good"
data2$HSD010_1[data2$HSD010 == 4]<-"Fair"
data2$HSD010_1[data2$HSD010 == 5]<-"Poor"

# Past wk # days cardiovascular exercise
#In this question you can include activities done in school. On how many of the past 7 days did {you/SP} exercise or participate in physical activity for at least 20 minutes that made {you/him/her} sweat and breathe hard, such as basketball, soccer, running, swimming laps, fast bicycling, fast dancing, or similar activities?

p <- data2 %>%
  group_by(HSD010_1) %>%
  summarise(aver=mean(PAQ677))%>%
  arrange(desc(aver))
p

p1 <- ggplot(p, aes(x=aver, y=fct_reorder(HSD010_1,aver))) + 
  geom_col() + 
  xlab("Number of Past wk days doing Cardiovascular Exercise ") + 
  ylab("Current Health Condition") + 
  theme_classic() +
  labs(title="Current Health Condition by Cardiovascular Exercise")
p1 
```

```{r}
#Second research question: how does the number of relate to the current helath condition

#PAQ678 - Past wk # days strengthened muscles: On how many of the past 7 days did {you/SP} do exercises to strengthen or tone {your/his/her} muscles, such as push-ups, sit-ups, or weight lifting?

#HSD010 - General health condition: 1-excellent, 2-very good, 3-good, 4-fair, 5-good.

data2 %>% 
  group_by(HSD010) %>%
  summarise(avg_time=mean(PAQ678)) %>%
  ggplot(aes(avg_time, HSD010))+
  geom_point()+
  geom_smooth(method='lm', formula= y~x, se=F)+
  scale_y_continuous(trans = "reverse")+
  theme_classic()+
  xlab("Number of Past wk days doing strengthened muscles exercises") + 
  ylab("Current Health Condition") + 
  labs(title="Correlation Between Average Days Of Strengthened Muscles Exercise And Current Health Condition")
```

